In [3]:
import pandas as pd

In [8]:
s = [10,20,30]
pd.Series(s)

0    10
1    20
2    30
dtype: int64

In [10]:
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [14]:
m = pd.Series([10,20,30,40],index = ['a','b','c','d'])

a    10
b    20
c    30
d    40
dtype: int64

In [15]:
n = pd.Series({1:'a',2:'b',3:'c'})
n

1    a
2    b
3    c
dtype: object

In [20]:
dataframe = {
    'Name': ['manoj','sham','shiva','ram','ravi'],
    'age':[23,35,43,22,21]
}
df = pd.DataFrame(dataframe)
df

    Name  age
0  manoj   23
1   sham   35
2  shiva   43
3    ram   22
4   ravi   21

In [49]:
df.sample(2)

   Name  Age
0  John   28
1  Anna   24

In [23]:
dd = pd.DataFrame([[1,2],[3,4]], columns = ['a','d'])
dd

   a  d
0  1  2
1  3  4

In [27]:
s1 =pd.Series([1,2])
s2 = pd.Series([3,4])
df = pd.DataFrame({'col1':s1,'col2':s2})
df

   col1  col2
0     1     3
1     2     4

In [29]:
aa = pd.DataFrame({ # creating data frame using dictionaries
    'Name': ['John', 'Anna'],
    'Age': [28, 24]
})
aa

   Name  Age
0  John   28
1  Anna   24

In [30]:
data = [# list of dictionary
    {'Name': 'John', 'Age': 28},
    {'Name': 'Anna', 'Age': 24}
]
df = pd.DataFrame(data)
data

[{'Name': 'John', 'Age': 28}, {'Name': 'Anna', 'Age': 24}]

In [38]:
df.shape

(2, 2)

In [39]:
df.columns

Index(['Name', 'Age'], dtype='object')

In [40]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [41]:
df.dtypes

Name    object
Age      int64
dtype: object

In [42]:
df.info

<bound method DataFrame.info of    Name  Age
0  John   28
1  Anna   24>

In [43]:
df.head(1)

   Name  Age
0  John   28

In [44]:
df.tail(1)

   Name  Age
1  Anna   24

In [45]:
df.sample(1)

   Name  Age
1  Anna   24

In [57]:
data[1]

{'Name': 'Anna', 'Age': 24}

In [59]:
data_list=[
    ['manoj','sai','ram'],
    [20,34,35],
    ['atp','hyd','tdp'],
    [200000,30000,4000]
]
data_list

[['manoj', 'sai', 'ram'],
 [20, 34, 35],
 ['atp', 'hyd', 'tdp'],
 [200000, 30000, 4000]]

In [64]:
data = [# list of dictionary
    {'Name': 'John', 'Age': 28},
    {'Name': 'Anna', 'Age': 24}
]
df = pd.DataFrame(data)
data

[{'Name': 'John', 'Age': 28}, {'Name': 'Anna', 'Age': 24}]

In [68]:
 df.rename( index = {0: 'full_name'},inplace = True)

In [73]:
Data = pd.DataFrame({
    'name' : ['manoj','sai','ram'],
    'age' : [12,23,34]
},index=['x','y','z'])
Data

    name  age
x  manoj   12
y    sai   23
z    ram   34

In [75]:
Data.loc['y','age']

np.int64(23)

In [77]:
Data.loc[['x','y','z'],['name']]

    name
x  manoj
y    sai
z    ram

In [78]:
Data.iloc[0]

name    manoj
age        12
Name: x, dtype: object

In [80]:
Data.iloc[1]

name    sai
age      23
Name: y, dtype: object

In [81]:
Data.iloc[1:,0:]

  name  age
y  sai   23
z  ram   34

In [82]:
Data.iloc[0:2,0:2]

    name  age
x  manoj   12
y    sai   23

In [83]:
Data[Data['age']>20]

  name  age
y  sai   23
z  ram   34

In [84]:
Data[(Data['age']>20) &(Data['age']<35)]

  name  age
y  sai   23
z  ram   34

In [91]:
Data[Data['age']==12]

    name  age
x  manoj   12

In [96]:
Data[Data['age']<12]

Empty DataFrame
Columns: [name, age]
Index: []

In [102]:
Data.loc[Data['age'] > 22, ['name']]

  name
y  sai
z  ram

In [101]:
Data[Data['age'] > 22] ['name']

y    sai
z    ram
Name: name, dtype: object

In [103]:
# 1
Data.loc[Data['age'] > 25, ['age']]

# 2
Data.loc[Data['name'] == 'x', ['age']]

Empty DataFrame
Columns: [age]
Index: []

In [105]:
Data[Data['name'].isin(['manoj','ram'])]

    name  age
x  manoj   12
z    ram   34

In [116]:
df = pd.DataFrame({
'name':['a','b','c','d','e','f'],
'age':[20,23,24,30,40,45],
'marks':[50,30,40,60,70,80]
})
df

  name  age  marks
0    a   20     50
1    b   23     30
2    c   24     40
3    d   30     60
4    e   40     70
5    f   45     80

In [119]:
df[df['marks']>50]

  name  age  marks
3    d   30     60
4    e   40     70
5    f   45     80

In [122]:
df.query('marks>50')

  name  age  marks
3    d   30     60
4    e   40     70
5    f   45     80

In [123]:
df.loc[df['marks']>30]

  name  age  marks
0    a   20     50
2    c   24     40
3    d   30     60
4    e   40     70
5    f   45     80

In [125]:
df.loc[df['marks']<50,'marks']=0
df

  name  age  marks
0    a   20     50
1    b   23      0
2    c   24      0
3    d   30     60
4    e   40     70
5    f   45     80

In [128]:
df['marks'].where(df['marks']>50,0)

0     0
1     0
2     0
3    60
4    70
5    80
Name: marks, dtype: int64

In [129]:
df[df['age'].between(20,25)]

  name  age  marks
0    a   20     50
1    b   23      0
2    c   24      0

In [130]:
df

  name  age  marks
0    a   20     50
1    b   23      0
2    c   24      0
3    d   30     60
4    e   40     70
5    f   45     80

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['A','B','C','D','E','F','G','H','I','J'],
    'Age': [20, 22, 25, 27, 30, 19, 24, 28, 21, 26],
    'Marks': [45, 67, 80, 55, 90, 35, 60, 75, 50, 85],
    'City': ['BLR','HYD','BLR','DEL','HYD','DEL','BLR','DEL','HYD','BLR']
})

In [3]:
df

  Name  Age  Marks City
0    A   20     45  BLR
1    B   22     67  HYD
2    C   25     80  BLR
3    D   27     55  DEL
4    E   30     90  HYD
5    F   19     35  DEL
6    G   24     60  BLR
7    H   28     75  DEL
8    I   21     50  HYD
9    J   26     85  BLR

In [4]:
#1. Get students with Marks between 60 and 80

df[df['Marks'].between(60,80)]

  Name  Age  Marks City
1    B   22     67  HYD
2    C   25     80  BLR
6    G   24     60  BLR
7    H   28     75  DEL

In [5]:
df[(df['Marks']>= 60) & (df['Marks']<=80)]

  Name  Age  Marks City
1    B   22     67  HYD
2    C   25     80  BLR
6    G   24     60  BLR
7    H   28     75  DEL

In [6]:
#2. Get students from 'BLR' city with Marks > 70
df[(df['City'] == 'BLR') & (df['Marks']>70)]

  Name  Age  Marks City
2    C   25     80  BLR
9    J   26     85  BLR

In [6]:
#3. Get Names of students whose Marks are either 45, 50, or 90
df[df['Marks'].isin([45,50,90])]

  Name  Age  Marks City
0    A   20     45  BLR
4    E   30     90  HYD
8    I   21     50  HYD

In [8]:
#4. Get rows where Age is NOT between 20 and 25
df[~df['Age'].between(20,25)]

  Name  Age  Marks City
3    D   27     55  DEL
4    E   30     90  HYD
5    F   19     35  DEL
7    H   28     75  DEL
9    J   26     85  BLR

In [9]:
#5Create a new column Result
#Marks ≥ 60 → "Pass"
#Marks < 60 → "Fail"
df['Result']= np.where(df['Marks']>=60,'pass','fail')
df

  Name  Age  Marks City Result
0    A   20     45  BLR   fail
1    B   22     67  HYD   pass
2    C   25     80  BLR   pass
3    D   27     55  DEL   fail
4    E   30     90  HYD   pass
5    F   19     35  DEL   fail
6    G   24     60  BLR   pass
7    H   28     75  DEL   pass
8    I   21     50  HYD   fail
9    J   26     85  BLR   pass

In [10]:
#Using .loc[]
df.loc[df['Marks'] >= 60, 'Result'] = 'Pass'
df.loc[df['Marks'] < 60, 'Result'] = 'Fail'

In [12]:
#6. Update Marks:
#If Marks < 50 → 0
#If Marks > 80 → 100
df.loc[df['Marks']<50,'Marks']=0
df.loc[df['Marks']>80,'Marks']=100
print(df)

  Name  Age  Marks City Result
0    A   20      0  BLR   Fail
1    B   22     67  HYD   Pass
2    C   25     80  BLR   Pass
3    D   27     55  DEL   Fail
4    E   30    100  HYD   Pass
5    F   19      0  DEL   Fail
6    G   24     60  BLR   Pass
7    H   28     75  DEL   Pass
8    I   21     50  HYD   Fail
9    J   26    100  BLR   Pass

In [13]:
#7. Get top 3 students with highest Marks
df.nlargest(3,'Marks')

  Name  Age  Marks City Result
4    E   30    100  HYD   Pass
9    J   26    100  BLR   Pass
2    C   25     80  BLR   Pass

In [14]:
df.nsmallest(3,'Marks')

  Name  Age  Marks City Result
0    A   20      0  BLR   Fail
5    F   19      0  DEL   Fail
8    I   21     50  HYD   Fail

In [17]:
#8. Sort data by Age (descending) and Marks (ascending)
df.sort_values(by=['Age','Marks'],ascending=[False,True])

  Name  Age  Marks City Result
4    E   30    100  HYD   Pass
7    H   28     75  DEL   Pass
3    D   27     55  DEL   Fail
9    J   26    100  BLR   Pass
2    C   25     80  BLR   Pass
6    G   24     60  BLR   Pass
1    B   22     67  HYD   Pass
8    I   21     50  HYD   Fail
0    A   20      0  BLR   Fail
5    F   19      0  DEL   Fail

In [20]:
#9. Count how many students are in each City
df['City'].value_counts()

City
BLR    4
HYD    3
DEL    3
Name: count, dtype: int64

In [10]:
#10.Get average Marks for each City
df.groupby('City')['Marks'].mean()

City
BLR    67.5
DEL    55.0
HYD    69.0
Name: Marks, dtype: float64

In [12]:
df.groupby('City')['Marks'].mean()

City
BLR    67.5
DEL    55.0
HYD    69.0
Name: Marks, dtype: float64

In [14]:
df.loc[df['Age']>20]

  Name  Age  Marks City
1    B   22     67  HYD
2    C   25     80  BLR
3    D   27     55  DEL
4    E   30     90  HYD
6    G   24     60  BLR
7    H   28     75  DEL
8    I   21     50  HYD
9    J   26     85  BLR

In [15]:
df.loc[df['Age']>20]

  Name  Age  Marks City
1    B   22     67  HYD
2    C   25     80  BLR
3    D   27     55  DEL
4    E   30     90  HYD
6    G   24     60  BLR
7    H   28     75  DEL
8    I   21     50  HYD
9    J   26     85  BLR

In [16]:
df[df['City']=='BLR']

  Name  Age  Marks City
0    A   20     45  BLR
2    C   25     80  BLR
6    G   24     60  BLR
9    J   26     85  BLR

In [18]:
df[(df['Marks']>60)& (df['City']=='HYD')]

  Name  Age  Marks City
1    B   22     67  HYD
4    E   30     90  HYD

In [19]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['A', 'B', 'C', 'D', 'D'],
    'Age': [20, np.nan, 25, 30, 30],
    'Marks': [80, 90, None, 70, 70],
    'City': ['BLR', 'HYD', 'BLR', None, None]
})

print(df)

  Name   Age  Marks  City
0    A  20.0   80.0   BLR
1    B   NaN   90.0   HYD
2    C  25.0    NaN   BLR
3    D  30.0   70.0  None
4    D  30.0   70.0  None

In [22]:
df.isna()

    Name    Age  Marks   City
0  False  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4  False  False  False   True

In [23]:
df.isnull()

    Name    Age  Marks   City
0  False  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4  False  False  False   True

In [24]:
df.isnull().sum()

Name     0
Age      1
Marks    1
City     2
dtype: int64

In [30]:
df['City'] = df['City'].fillna('Unknown')
df

  Name   Age  Marks     City
0    A  20.0   80.0      BLR
1    B   NaN   90.0      HYD
2    C  25.0    NaN      BLR
3    D  30.0   70.0  unknown
4    D  30.0   70.0  unknown

In [33]:
df['Age'].fillna(df['Age'].mean())
df

  Name    Age  Marks     City
0    A  20.00   80.0      BLR
1    B  26.25   90.0      HYD
2    C  25.00    NaN      BLR
3    D  30.00   70.0  unknown
4    D  30.00   70.0  unknown

In [35]:
df['City'].fillna('Unknown')
df

  Name    Age  Marks     City
0    A  20.00   80.0      BLR
1    B  26.25   90.0      HYD
2    C  25.00    NaN      BLR
3    D  30.00   70.0  unknown
4    D  30.00   70.0  unknown

In [36]:
df.dropna()

  Name    Age  Marks     City
0    A  20.00   80.0      BLR
1    B  26.25   90.0      HYD
3    D  30.00   70.0  unknown
4    D  30.00   70.0  unknown

In [41]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [45]:
df.drop_duplicates()

  Name    Age  Marks     City
0    A  20.00   80.0      BLR
1    B  26.25   90.0      HYD
2    C  25.00    NaN      BLR
3    D  30.00   70.0  unknown

In [48]:
df['City'].str.strip()

0        BLR
1        HYD
2        BLR
3    unknown
4    unknown
Name: City, dtype: object

In [51]:
df['City'].str.upper()

0        BLR
1        HYD
2        BLR
3    UNKNOWN
4    UNKNOWN
Name: City, dtype: object

In [52]:
df['City'].str.lower()

0        blr
1        hyd
2        blr
3    unknown
4    unknown
Name: City, dtype: object

In [56]:
df.rename(columns={'Marks':'Score'},inplace = True)
df

  Name    Age  Score     City
0    A  20.00   80.0      BLR
1    B  26.25   90.0      HYD
2    C  25.00    NaN      BLR
3    D  30.00   70.0  unknown
4    D  30.00   70.0  unknown

In [59]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['A','B','C','D','E','E','F','G'],
    'Age': [20, 22, np.nan, 25, 30, 30, -5, 40],
    'Marks': [80, 90, None, 70, 200, 200, 50, 60],
    'City': ['BLR','HYD','blr','Bangalore','HYD',None,'CHE','CHE'],
    'Date': ['2023-01-01','2023-02-01','invalid','2023-03-01',
             '2023-04-01','2023-04-01','2023-05-01','2023-06-01']
})

In [60]:
df

  Name   Age  Marks       City        Date
0    A  20.0   80.0        BLR  2023-01-01
1    B  22.0   90.0        HYD  2023-02-01
2    C   NaN    NaN        blr     invalid
3    D  25.0   70.0  Bangalore  2023-03-01
4    E  30.0  200.0        HYD  2023-04-01
5    E  30.0  200.0       None  2023-04-01
6    F  -5.0   50.0        CHE  2023-05-01
7    G  40.0   60.0        CHE  2023-06-01

In [62]:
#1. Find missing values in each column
df.isnull().sum()

Name     0
Age      1
Marks    1
City     1
Date     0
dtype: int64

In [70]:
#2. Fill missing Age with mean
df['Age'].fillna(df['Age'].mean())

0    20.000000
1    22.000000
2    23.142857
3    25.000000
4    30.000000
5    30.000000
6    -5.000000
7    40.000000
Name: Age, dtype: float64

In [71]:
#3. Drop rows where Marks is missing
df.dropna(subset=['Marks'])

  Name   Age  Marks       City        Date
0    A  20.0   80.0        BLR  2023-01-01
1    B  22.0   90.0        HYD  2023-02-01
3    D  25.0   70.0  Bangalore  2023-03-01
4    E  30.0  200.0        HYD  2023-04-01
5    E  30.0  200.0       None  2023-04-01
6    F  -5.0   50.0        CHE  2023-05-01
7    G  40.0   60.0        CHE  2023-06-01

In [75]:
#4. Remove duplicate rows
df = df.drop_duplicates()

In [77]:
#5. Fix negative Age values
df = df[df['Age'] > 0]
df

  Name        Age  Marks       City        Date
0    A  20.000000   80.0        BLR  2023-01-01
1    B  22.000000   90.0        HYD  2023-02-01
2    C  23.142857    NaN        blr     invalid
3    D  25.000000   70.0  Bangalore  2023-03-01
4    E  30.000000  200.0        HYD  2023-04-01
5    E  30.000000  200.0       None  2023-04-01
7    G  40.000000   60.0        CHE  2023-06-01

In [81]:
# 6. Remove Marks greater than 100 (invalid data)
df[df['Marks'] <= 100]

  Name   Age  Marks       City        Date
0    A  20.0   80.0        BLR  2023-01-01
1    B  22.0   90.0        HYD  2023-02-01
3    D  25.0   70.0  Bangalore  2023-03-01
7    G  40.0   60.0        CHE  2023-06-01

In [82]:
#7. Convert City to lowercase
df['City'].str.lower()

0          blr
1          hyd
3    bangalore
7          che
Name: City, dtype: object

In [84]:
#8. Standardize city names
df['City'].replace({
    'blr': 'bangalore',
    'bangalore': 'bangalore'
})
df

  Name   Age  Marks       City        Date
0    A  20.0   80.0        BLR  2023-01-01
1    B  22.0   90.0        HYD  2023-02-01
3    D  25.0   70.0  Bangalore  2023-03-01
7    G  40.0   60.0        CHE  2023-06-01

In [ ]:
#9. Fill missing City with "unknown"
 df['City'].fillna('unknown')

In [2]:
#merging
import pandas as pd

df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['A', 'B', 'C']
})

df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'Marks': [70, 80, 90]
})

In [6]:
print(df1)

   ID Name
0   1    A
1   2    B
2   3    C

In [7]:
print(df2)

   ID  Marks
0   2     70
1   3     80
2   4     90

In [8]:
#inner join
pd.merge(df1,df2,on='ID',how='inner')

   ID Name  Marks
0   2    B     70
1   3    C     80

In [9]:
pd.merge(df1,df2,on='ID',how='left')

   ID Name  Marks
0   1    A    NaN
1   2    B   70.0
2   3    C   80.0

In [10]:
pd.merge(df1,df2,on='ID',how='right')

   ID Name  Marks
0   2    B     70
1   3    C     80
2   4  NaN     90

In [23]:
pd.merge(df1,df2,on='ID',how='outer', indicator=True)

   ID Name  Marks      _merge
0   1    A    NaN   left_only
1   2    B   70.0        both
2   3    C   80.0        both
3   4  NaN   90.0  right_only

In [22]:
pd.merge(df1,df2,on=['ID','ID'])

   ID Name  Marks
0   2    B     70
1   3    C     80

In [25]:
pd.merge(df1,df2,left_index=True,right_index=True)

   ID_x Name  ID_y  Marks
0     1    A     2     70
1     2    B     3     80
2     3    C     4     90

In [27]:
pd.merge(df1,df2)

   ID Name  Marks
0   2    B     70
1   3    C     80

In [28]:
pd.concat([df1,df2])

   ID Name  Marks
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   2  NaN   70.0
1   3  NaN   80.0
2   4  NaN   90.0

In [29]:
pd.concat([df2,df1])

   ID  Marks Name
0   2   70.0  NaN
1   3   80.0  NaN
2   4   90.0  NaN
0   1    NaN    A
1   2    NaN    B
2   3    NaN    C

In [31]:
#rows base concat
pd.concat([df1,df2],axis=1)

   ID Name  ID  Marks
0   1    A   2     70
1   2    B   3     80
2   3    C   4     90

In [1]:
# Valid Dataset (one_to_many)
import pandas as pd

# Customers (ONE side)
customers = pd.DataFrame({
    'CustomerID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

# Orders (MANY side)
orders = pd.DataFrame({
    'CustomerID': [1, 1, 2, 3, 3],
    'OrderID': [101, 102, 103, 104, 105],
    'Amount': [250, 300, 150, 400, 500]
})

In [2]:
customers

   CustomerID     Name
0           1    Alice
1           2      Bob
2           3  Charlie

In [3]:
orders

   CustomerID  OrderID  Amount
0           1      101     250
1           1      102     300
2           2      103     150
3           3      104     400
4           3      105     500

In [7]:
merge = pd.merge(customers,orders,on='CustomerID',validate='one_to_many')
merge

   CustomerID     Name  OrderID  Amount
0           1    Alice      101     250
1           1    Alice      102     300
2           2      Bob      103     150
3           3  Charlie      104     400
4           3  Charlie      105     500

In [9]:
# Students many_to_many
students = pd.DataFrame({
    'StudentID': [1, 2, 3],
    'Name': ['A', 'B', 'C']
})

# Enrollments (bridge table)
enrollments = pd.DataFrame({
    'StudentID': [1, 1, 2, 3, 3],
    'CourseID': ['C1', 'C2', 'C1', 'C2', 'C3']
})

# Courses
courses = pd.DataFrame({
    'CourseID': ['C1', 'C2', 'C3'],
    'CourseName': ['Math', 'Science', 'English']
})

# Merge step-by-step
df = pd.merge(students, enrollments, on='StudentID', validate='one_to_many')
final = pd.merge(df, courses, on='CourseID', validate='many_to_one')

print(final)

   StudentID Name CourseID CourseName
0          1    A       C1       Math
1          1    A       C2    Science
2          2    B       C1       Math
3          3    C       C2    Science
4          3    C       C3    English

In [10]:
# group and aggeration 
import pandas as pd

sales = pd.DataFrame({
    'OrderID': [101,102,103,104,105,106,107,108,109,110],
    'Region': ['North','South','East','West','North','South','East','West','North','East'],
    'Product': ['Laptop','Mobile','Laptop','Tablet','Mobile','Laptop','Tablet','Mobile','Tablet','Laptop'],
    'SalesPerson': ['A','B','C','D','A','B','C','D','A','C'],
    'Amount': [50000,20000,55000,15000,22000,52000,18000,21000,17000,53000],
    'Quantity': [5,2,6,3,2,5,2,3,2,5]
})

In [11]:
sales

   OrderID Region Product SalesPerson  Amount  Quantity
0      101  North  Laptop           A   50000         5
1      102  South  Mobile           B   20000         2
2      103   East  Laptop           C   55000         6
3      104   West  Tablet           D   15000         3
4      105  North  Mobile           A   22000         2
5      106  South  Laptop           B   52000         5
6      107   East  Tablet           C   18000         2
7      108   West  Mobile           D   21000         3
8      109  North  Tablet           A   17000         2
9      110   East  Laptop           C   53000         5

In [15]:
# grouped gy salesperson
sale =sales.groupby('SalesPerson')
sale
for i,v in sale:
    print(i)
    print(v)

A
   OrderID Region Product SalesPerson  Amount  Quantity
0      101  North  Laptop           A   50000         5
4      105  North  Mobile           A   22000         2
8      109  North  Tablet           A   17000         2
B
   OrderID Region Product SalesPerson  Amount  Quantity
1      102  South  Mobile           B   20000         2
5      106  South  Laptop           B   52000         5
C
   OrderID Region Product SalesPerson  Amount  Quantity
2      103   East  Laptop           C   55000         6
6      107   East  Tablet           C   18000         2
9      110   East  Laptop           C   53000         5
D
   OrderID Region Product SalesPerson  Amount  Quantity
3      104   West  Tablet           D   15000         3
7      108   West  Mobile           D   21000         3

In [16]:
sale =sales.groupby('SalesPerson')
sale

In [17]:
sale =sales.groupby('SalesPerson')['Amount'].sum()
sale

SalesPerson
A     89000
B     72000
C    126000
D     36000
Name: Amount, dtype: int64

In [18]:
product_sum = sales.groupby('Product')['Amount'].sum()
product_sum

Product
Laptop    210000
Mobile     63000
Tablet     50000
Name: Amount, dtype: int64

In [22]:
region = sales.groupby('Region')['Amount'].sum()
region

Region
East     126000
North     89000
South     72000
West      36000
Name: Amount, dtype: int64

In [25]:
data=sales.groupby(['Region','Product','Quantity','SalesPerson'])['Amount'].sum()
data

Region  Product  Quantity  SalesPerson
East    Laptop   5         C              53000
                 6         C              55000
        Tablet   2         C              18000
North   Laptop   5         A              50000
        Mobile   2         A              22000
        Tablet   2         A              17000
South   Laptop   5         B              52000
        Mobile   2         B              20000
West    Mobile   3         D              21000
        Tablet   3         D              15000
Name: Amount, dtype: int64

In [29]:
sales['Amount'].mean()

21500.0

In [30]:
sales['Amount'].median()

21500.0

In [31]:
sales['Amount'].std()

17537.57870022731

In [33]:
sales['Region'].count()

np.int64(10)

In [35]:
sales['Amount'].agg(['sum','min','max','mean','count','std','median'])

sum       323000.0000
min        15000.0000
max        55000.0000
mean       32300.0000
count         10.0000
std        17537.5787
median     21500.0000
Name: Amount, dtype: float64

In [1]:
import pandas as pd

sales = pd.DataFrame({
    'OrderID': [101,102,103,104,105,106,107,108,109,110],
    'Region': ['North','South','East','West','North','South','East','West','North','East'],
    'Product': ['Laptop','Mobile','Laptop','Tablet','Mobile','Laptop','Tablet','Mobile','Tablet','Laptop'],
    'SalesPerson': ['A','B','C','D','A','B','C','D','A','C'],
    'Amount': [50000,20000,55000,15000,22000,52000,18000,21000,17000,53000],
    'Quantity': [5,2,6,3,2,5,2,3,2,5]
})
sales

   OrderID Region Product SalesPerson  Amount  Quantity
0      101  North  Laptop           A   50000         5
1      102  South  Mobile           B   20000         2
2      103   East  Laptop           C   55000         6
3      104   West  Tablet           D   15000         3
4      105  North  Mobile           A   22000         2
5      106  South  Laptop           B   52000         5
6      107   East  Tablet           C   18000         2
7      108   West  Mobile           D   21000         3
8      109  North  Tablet           A   17000         2
9      110   East  Laptop           C   53000         5

In [5]:
#1Total sales per Region
sales.groupby('Region')['Amount'].sum()

Region
East     126000
North     89000
South     72000
West      36000
Name: Amount, dtype: int64

In [8]:
#Average sales per Product
sales.groupby('Product')['Amount'].mean()

Product
Laptop    52500.000000
Mobile    21000.000000
Tablet    16666.666667
Name: Amount, dtype: float64

In [11]:
#3Count number of orders per SalesPerson
sales.groupby('SalesPerson')['OrderID'].count()

SalesPerson
A    3
B    2
C    3
D    2
Name: OrderID, dtype: int64

In [12]:
4#Total and average sales per Region
sales.groupby('Region')['Amount'].agg(['sum','mean'])

           sum          mean
Region
East    126000  42000.000000
North    89000  29666.666667
South    72000  36000.000000
West     36000  18000.000000

In [14]:
#5Total quantity sold per Product
sales.groupby('Product')['Quantity'].sum()

Product
Laptop    21
Mobile     7
Tablet     7
Name: Quantity, dtype: int64

In [16]:
#6Max and Min sales per Region
sales.groupby('Region')['Amount'].agg(['max','min'])

          max    min
Region
East    55000  18000
North   50000  17000
South   52000  20000
West    21000  15000